config/routes.rb
# frozen_string_literal: true

require 'resque/server'
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  mount Resque::Server.new, at: '/resque', constraints: AdminConstraint.new
  get 'sign_in', to: 'sessions#new', as: :new_session
  post 'sign_in', to: 'sessions#create', as: :session
  delete 'sign_out', to: 'sessions#destroy', as: :destroy_session

  get 'forgot_password', to: 'passwords#new', as: :new_password
  post 'forgot_password', to: 'passwords#create', as: :reset_password
  get 'reset_password', to: 'passwords#edit', as: :edit_password
  patch 'reset_password', to: 'passwords#update', as: :update_password
  get 'set_password', to: 'passwords#set', as: :set_password
  patch 'set_password', to: 'passwords#confirm', as: :confirm_password

  get 'sign_up', to: 'registrations#new', as: :new_sign_up
  post 'sign_up', to: 'registrations#create', as: :sign_up
  get 'profile', to: 'registrations#edit', as: :edit_profile
  put 'profile', to: 'registrations#update', as: :update_profile
  resources :accounts do
    get :history, on: :member
    get :activity, on: :member
    get :billing, on: :member
      resources :lists do
        get :index, on: :member
        get :history, on: :member
      end
      resources :records_transactions, except: %i(index)
      resources :users, except: %i(destroy) do
        get :history, on: :member
      end
      resources :products do
        get :index, on: :member
        get :history, on: :member
      end
  end
  resources :lists do
    get :index, on: :member
    get :show, on: :member
  end
  resources :products
  resources :users, except: %i(destroy) do
    get :history, on: :member
    resources :features, only: %i(index update)
  end

  get 'admin', to: 'admin#index'
  root :to => 'home#index'

  resources :users
end

app/models/account.rb
# frozen_string_literal: true

class Account < ApplicationRecord
  include Usable
  include ApiAccessible
  include Core
  include RecordCountable
  include Searchable
  include Stripe


  audited except: :updated_at
  has_associated_audits

  validates :name, presence: true

  has_secure_token :invite_token

  scope :activity, lambda { |account|
    account
      .associated_audits
      .where.not(auditable_type: %w(User RecordTransaction))
      .order(created_at: :desc, id: :desc)
  }

  def current?
    Current.account == self
  end
end

app/models/account/api_accessible.rb
# frozen_string_literal: true

module Account::ApiAccessible
  extend ActiveSupport::Concern

  included do
    has_many :api_requests, dependent: :destroy
    has_secure_token :api_token
  end
end

app/models/account/core.rb
# frozen_string_literal: true

module Account::Core
  extend ActiveSupport::Concern

  included do
    belongs_to :core_account, class_name: 'Core::Account', optional: true
    has_many :orders, through: :core_account
    has_many :invoices, through: :core_account
  end
end

app/models/account/record_countable.rb
# frozen_string_literal: true

module Account::RecordCountable
  extend ActiveSupport::Concern

  included do
    has_many :record_transactions
    has_many :lists, through: :users
  end

  def available_records
    total_records - used_records
  end

  def total_records
    record_transactions.sum(:record_count)
  end

<<<<<<< HEAD

=======
  def used_records
    lists.where(list_type: 'audience').sum(:record_count)
  end
>>>>>>> origin/main
end

app/models/account/searchable.rb
# frozen_string_literal: true

module Account::Searchable
  extend ActiveSupport::Concern

  included do
    scope :search, ->(search) { where('name LIKE :q', q: "%#{search}%") }
  end
end

app/models/account/stripe.rb
# frozen_string_literal: true

module Account::Stripe
  extend ActiveSupport::Concern

  def stripe_id
    super || create_stripe_customer!
  end

  def create_stripe_customer!
    fail 'Currenly only supported for CORE transactions' if core_account.blank?

    customer = Stripe::Customer.create(
      address: {
        city: core_account.city,
        country: 'US',
        line1: core_account.address,
        line2: core_account.address2,
        postal_code: core_account.zip,
        state: core_account.state
      },
      email: core_account.primary_user.email,
      name:
    )
    update!(stripe_id: customer.id)
    customer.id
  end
end

app/models/account/usable.rb
# frozen_string_literal: true

module Account::Usable
  extend ActiveSupport::Concern

  included do
    has_many :users, dependent: :destroy
  end
end

app/models/core/account.rb
# frozen_string_literal: true

class Core::Account < Core::Record
  include Syncable

  self.table_name = 'accounts'

  belongs_to :primary_user, class_name: 'Core::User', foreign_key: :primary_user
  has_many :account_users, class_name: 'Core::AccountUser', foreign_key: :account_id
  has_many :users, through: :account_users
  belongs_to :rep, class_name: 'Core::User', foreign_key: :rep_id

  has_many :orders, class_name: 'Core::Order', foreign_key: :client
  has_many :invoices, through: :orders
  has_many :sans, through: :orders, source: :san_record

  def uo_account
    @uo_account ||= Account.find_by(core_account: self)
  end

  def full_address
    Address.new(address:, address2:, city:, state:, zip:)
  end

  def last_nonexempt_san
    sans.joins(:order)
      .where(exempt: false, orders: { san: true })
      .where(Core::Order.arel_table[:status].gteq(Core::Order.statuses['approved_by_client']))
      .where(Core::San.arel_table[:expiration].gt(Time.now))
      .order(created: :desc)
      .limit(1)
      .first || {}
  end
end

app/models/core/account/syncable.rb
# frozen_string_literal: true

module Core::Account::Syncable
  extend ActiveSupport::Concern
  include Loggable

  class SyncError < StandardError; end

  class_methods do
    def sync
      Core::Account.find_each(&:sync_later)
    end
  end

  def sync_later
    Core::SyncAccountJob.perform_later(id)
  end

  def sync!
    log "Creating UO account for CORE account #{id}"

    ActiveRecord::Base.transaction do
      uo_account = existing_uo_account || Account.new(name: company_name.presence || 'Unknown')
      uo_account.update!(core_account: self)

      account_users.where(removed: false).find_each do |account_user|
        account_user.user.sync(uo_account)
      end

      uo_account
    end
  end

  private

  def existing_uo_account
    uo_account = existing_uo_accounts.first
    return uo_account if uo_account&.core_account.blank? || uo_account.core_account == self

    fail SyncError, 'UO account already linked to another CORE account'
  end

  def existing_uo_accounts
    uo_users = User.where(email: account_users.where(removed: false).map { |au| au.user.email })
    uo_accounts = uo_users.map(&:account).uniq

    fail SyncError, 'Users belong to multiple VIA accounts' if uo_accounts.size > 1

    uo_accounts
  end
end

app/controllers/accounts_controller.rb
# frozen_string_literal: true

class AccountsController < ApplicationController
  include Searchable
  include Pageable

  feature :account_management, only: :index

  before_action :set_account, except: :index
  before_action :redirect_unauthorized, unless: :authorized?, except: :index

  def index
    @pagy, @accounts = pagy(Account.search(@search))
  end

  def show; end

  def edit; end

  def update
    if @account.update(account_params)
      redirect_to @account, notice: I18n.t('accounts.updated', name: @account.name)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def history
    @pagy, @history = pagy(@account.audits.reorder(created_at: :desc, id: :desc))
  end

  def activity
    @pagy, @history = pagy(Account.activity(@account))
  end

  def billing
    @pagy, @invoices = pagy(@account.invoices)
  end

  private

  def set_account
    @account = Account.find(params[:id])
  end

  def authorized?
    return true if Feature.enabled? :account_management
    return false if Current.account != @account

    action_name == 'activity' || Feature.enabled?(:account_admin)
  end

  def account_params
    params.require(:account).permit(:name)
  end
end

app/views/accounts/activity.html.erb
<%= title t('audits.activity_log_title') %>
<%= subtitle @account.name %>

<% if @history.blank? %>
  <div class="flex items-center justify-center text-gray-400 py-8">
    <%= t('dashboard.no_activity') %>
  </div>
<% else %>
  <%= tables_table pagy: @pagy, entry_name: 'record' do |table| %>
    <%= table.header_cell name: t('views.table.user'), classes: 'w-1/5' %>
    <%= table.header_cell name: t('views.table.action'), classes: 'w-20' %>
    <%= table.header_cell name: t('views.table.type'), classes: 'w-28' %>
    <%= table.header_cell name: t('views.table.name'), classes: 'w-1/3' %>
    <%= table.header_cell name: t('views.table.when'), classes: 'w-48' %>

    <% @history.each do |record| %>
      <%= table.row do |row| %>
        <%= row.cell classes: 'truncate' do %>
          <% if record.user.present? %>
            <%= avatar user: record.user, with_name: true %>
          <% else %>
            <span class="text-gray-400">N/A</span>
          <% end %>
        <% end %>

        <%= row.cell do %>
          <%= audit_action_label audit: record %>
        <% end %>

        <%= row.cell do %>
          <%= record.auditable_type %>
        <% end %>

        <%= row.cell classes: 'truncate' do %>
          <%= audits_name audit: record %>
        <% end %>

        <%= row.cell do %>
          <%= short_time at: record.created_at %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/accounts/billing.html.erb
<%= title t('accounts.billing') %>
<%= subtitle @account.name %>

<%= content_for :navigation_actions do %>
  <%= button(
    text: t('accounts.buttons.edit_payment_method'),
    url: '',
    icon: 'credit-card',
    classes: 'mr-2'
  ) %>
  <%= button(
    text: t('accounts.buttons.edit_subscription'),
    url: '',
    icon: 'rotate',
    classes: 'mr-2'
  ) %>
<% end %>

<% if @invoices.empty? %>
  <%= empty_state do %>
    <%= t('accounts.invoices.empty') %>
  <% end %>
<% else %>
  <h2 class="text-lg mb-2 font-bold"><%= t('accounts.invoices.title') %></h2>

  <%= tables_table pagy: @pagy, entry_name: 'invoice' do |table| %>
    <%= table.header_cell name: t('views.table.id'), classes: 'w-32' %>
    <%= table.header_cell name: t('views.table.date'), classes: 'w-48' %>
    <%= table.header_cell name: t('views.table.amount'), classes: 'w-60' %>
    <% @invoices.order(created: :desc).each do |invoice| %>
      <%= table.row url: invoice_path(invoice) do |row| %>
        <%= row.cell do %>
          <%= invoice.order_id %>
        <% end %>
        <%= row.cell do %>
          <%= local_time(invoice.created, '%B %-e, %Y') %>
        <% end %>
        <%= row.cell do %>
          <%= number_to_currency(invoice.amount) %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/accounts/edit.html.erb
<%= title t('accounts.edit') %>

<div class="max-w-lg">
  <%= form_with model: @account do |form| %>
    <%= cards_card do %>
      <%= cards_field do %>
        <%= forms_field(
          form: form,
          field: :name,
          required: true,
          label: 'Name'
        ) %>
      <% end %>

      <div class="mt-6 text-right">
        <%= button(
          text: 'Save',
          type: :submit,
          icon: 'check',
          color: 'green',
          show_loading: true
        ) %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/accounts/history.html.erb
<%= title t('audits.history') %>
<%= subtitle @account.name %>

<%= render 'history' %>

app/views/accounts/index.html.erb
<%= title t('accounts.title') %>

<%= page_header_search url: accounts_path, value: @search, placeholder: 'Search accounts' %>

<% if @accounts.empty? %>
  <p class="text-center text-lg p-20 text-gray-500">
    No accounts match the search.
  </p>
<% else %>
  <%= tables_table pagy: @pagy, entry_name: 'account' do |table| %>
    <%= table.header_cell name: t('views.table.name'), classes: 'w-full' %>

    <% @accounts.each do |account| %>
      <%= table.row url: [account].compact do |row| %>
        <%= row.cell classes: 'truncate' do %>
          <%= account.name %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/accounts/show.html.erb
<%= title @account.name %>

<%= content_for :navigation_actions do %>
  <%= button(
    text: t('accounts.buttons.users'),
    url: [@account, :users],
    icon: 'users',
    classes: 'mr-2'
  ) %>
  <%= button(
    text: t('accounts.buttons.edit'),
    url: [:edit, @account],
    icon: 'pencil',
    classes: 'mr-2'
  ) %>
  <% if Feature.enabled? :account_management %>
    <%= button(
      text: t('accounts.buttons.add_records'),
      url: [:new, @account, :record_transaction],
      icon: 'file-plus',
      classes: 'mr-2'
    ) %>
  <% else %>
    <%= button(
      text: t('accounts.buttons.billing'),
      url: [:billing, @account],
      icon: 'file-invoice-dollar',
      classes: 'mr-2'
    ) %>
  <% end %>
  <%= button(
    text: t('audits.history'),
    url: [:history, @account],
    icon: 'clock-rotate-left'
  ) %>
<% end %>

<% if Feature.enabled? :account_management %>
  <%= cards_card do %>
    <%= detail name: t('accounts.available_records') do %>
      <%= number_with_delimiter(@account.available_records) %> / <%= number_with_delimiter(@account.total_records) %>
    <% end %>

    <%= detail url: [@account, :products] do %>
      <div class="flex items-center font-semibold text-gray-600 dark:text-gray-300">
        <%= icon name: 'screen-users', class: 'w-6 h-6 mr-3 text-blue' %>
        <%= t('products.title') %>
      </div>
    <% end %>

    <%= detail url: [@account, :lists] do %>
      <div class="flex items-center font-semibold text-gray-600 dark:text-gray-300">
        <%= icon name: 'address-card', class: 'w-6 h-6 mr-3 text-green' %>
        <%= t('lists.title') %>
      </div>
    <% end %>
  <% end %>

  <div class="mt-12">
    <h2 class="text-center text-lg mb-2 font-bold"><%= t('record_transactions.title') %></h2>

    <%= tables_table do |table| %>
      <%= table.header_cell name: t('views.table.date') %>
      <%= table.header_cell name: t('views.table.record_count') %>

      <% @account.record_transactions.order(created_at: :desc).each do |record_transaction| %>
        <%= table.row url: [@account, record_transaction].compact do |row| %>
          <%= row.cell do %>
            <%= local_time(record_transaction.created_at, '%m/%d/%y %l:%M %p') %>
          <% end %>

          <%= row.cell do %>
            +<%= number_with_delimiter(record_transaction.record_count) %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>
<% else %>
  <%= cards_card(
    title: t('users.views.api'),
    icon: 'cloud-bolt',
    color: :orange,
    classes: 'flex-1 max-w-lg mt-4 lg:mt-0'
  ) do %>
    <div data-controller="clipboard" data-clipboard-success-content=<%= t('users.buttons.copy.copied') %>>
      <div class="mb-2 flex items-center pr-6">
        <div class="leading-5 text-gray-700 dark:text-gray-300 font-semibold">
          <label class="block" for="key"><%= t('users.views.api_key') %></label>
        </div>
      </div>
      <input
        readonly
        id="key"
        type="text"
        value="<%= Current.account.api_token %>"
        data-clipboard-target="source"
        class="<%= class_string(field_classes) %>"
      />

      <div class="mt-6 text-right">
        <%= button(
          text: t('users.buttons.copy.clipboard'),
          icon: 'clipboard',
          type: 'button',
          data: {
            action: 'clipboard#copy',
            'clipboard-target': 'button'
          }
        ) %>
      </div>
    </div>
  <% end %>
<% end %>